<p>
    An dem Wochenende vom 17. - 19.09.  ging es für Felix Pembaur und Jan Küpper wieder weiter, die Beiden starteten in Bad Dürrheim beim Riderman. Ein Etappenrennen über drei Tage.

    Los ging es für die fast 500 Starter am Freitag beim Einzelzeitfahren über 16 km mit 200 hm. Jan machte um 16:43 Uhr den Anfang gefolgt von Felix um 17:05 Uhr, so begegneten sich die beiden gerade noch auf der Start- / Zielgerade. Jan fuhr die 16 km in einer Zeit von 00:26:24 und Felix in 00:25:06. Das bedeuten die Plätze 299 und 188 für die beiden.

    Am Samstag folgte die zweite Etappe mit einem Straßenrennen über 120 km mit 2000 hm. Noch bis kurz vor dem Start wurde das Höhenprofil auswendig gelernt, dabei spielten die Kilometer 31 (1. Anstieg), 50 (2. Anstieg), 62 (3. Anstieg) und 2. Verpflegung bei Kilometer 86 die größte Rolle. Die ganzen zusätzlichen Bergwertungen wurden dabei vernachlässigt, da sich die beiden dort keine Chancen ausrechneten. Aus einer guten Ausgangsposition in Startblock 1 fiel um 12:05 Uhr der Startschuss. Felix positionierte sich gleich weit vorne im Feld und konnte das hohe Tempo an den Anstiegen mitgehen. Jan ließ sich ein paar Plätze zurückfallen und suchte sich eine Gruppe, in der er mitfahren konnte ohne sich gleich am ersten längeren Anstieg kaputt zu fahren. Bis ca. km 85 gelang es Felix das hohe Tempo der Spitzengruppe mitzufahren. Am letzten richtigen Anstieg, der sich als richtige Wand entpuppte, mussten er und weitere Fahrer allerdings reißen lassen und schafften es dann nicht wieder die Lücke zu schließen. Am Ende reichte es dann für Felix für Platz 43 und für Jan Platz 216 in der Tageswertung. In der Gesamtwertung bedeuten dass Platz 48 und 225 für das Duo.

    Mit gefühlt schweren Beinen vom Vortag starteten die beiden in den Tag. Nach dem Warmfahren fühlten sich diese zum Glück schon wieder ganz anders an und so ging es am Sonntag wieder in die Startaufstellung in Block 1. Das Streckenprofil versprach diesmal ein viel schnelleres Rennen mit 1000 hm auf 100km und nur einem langen Anstieg. Nach dem Startschuss um 11:00 Uhr blieb das Fahrerfeld zunächst eine längere Zeit sehr groß. Im weiteren zerlegte sich dieses dann in mehrere, wobei Felix sich wieder sehr weit vorne bei den Topfahren und dem gelben Trikot halten konnte. Am Ende beendete er das Rennen auf Platz 19 und Jan folgte 14 Minuten später auf Platz 235. Damit positionierten sich die beiden in der Gesamtwertung auf den Plätzen 44 und 208 gesamt, sowie 19 & 61 bei den Herren.

    Eine rundum tolle Veranstaltung, bestens organisiert und mit einer sehr schönen Streckenführung. Ganz nach dem Motto „Ride like a Pro“ wurden die Fahrer über das gesamte Rennen von Kameras und einem Helikopter begleitet, die das Renngeschehen live ins Internet gestreamt haben. Außerdem konnten sich alle Fahrer Verpflegung von Motorrädern nehmen, die sich im Fahrerfeld befanden.
</p>