<p>Aus einer Laune heraus entstand spontan die Idee mit dem Rad in den geplanten Sommerurlaub nach Süd Frankreich zu fahren.

    Nach dem ich selber schnell von der Idee überzeugt war, machte ich mir gleich Gedanken über mögliche Routen. Angepeilt habe ich eine Anfahrt unterteilt in drei Etappen, dass bedeuten für mich 400 - 500 km. Ein kurzer Blick auf die Karte ergab die möglichen Startorte Lyon in Frankreich, Genfersee in der Schweiz und Mailand in Italien. Erst mal erschienen mir Genf und Mailand auf Grund der Alpen am attraktivsten. Im Endeffekt entschieden die Reisekosten über den Startort meiner Reise. Über die Webseiten von Google flight und der Deutschen Bahn fand ich die günstigste Anreise mit einem Flug von Eurowings nach Mailand Malpense. Das ließ mich leicht schmunzeln, da ich genau diesen Flug bereits ein Jahr zuvor für den Sommerurlaub am Lago Maggiore gebucht hatte, ihn aber auf Grund der Pandemie stornieren musste. Zu beachten war für mich beim Flug besonders, dass die Airline es erlaubt das Rad in einem Karton aufzugeben, manche möchten es nur in einer Biketasch.
    Im nächsten Schritt informierte ich mich im Netz über die Mitnahme von Gepäck beim Bikepacking, für mich war klar, dass ich auf dem Rücken nur einen kleinen Rucksack tragen möchte und möglichst viel Gepäck am Rad. Von den Kommentaren wenig beeindruckt entschied ich mich für eine 13l Satteltasche für 60€. Als Campingfan schwebte in mir der Gedanke zwischen den Etappen auf Campingplätzen zu übernachten. Auf meiner Suche im Netz nach der optimalen Lösung entdeckte ich die dollstem Ideen, von Planen die über die aus dem Rahmen ausgebauten Laufräder gespannt waren bis zu Wurfzelt war alles dabei. Ich bestellte mir im Netz für 30€ ein Zelt, das in der Beschreibung zwischen zwei Bäumen aufgespannt werden konnte. Meine Idee war es das Zelt am auf den Kopf gestellten Fahrrad zu befestigen. Der lange Lieferzeitraum für die Bestellung aus China, die sogar meinen Reisezeitraum überschritt war mir doch zu riskant, so bestellte ich ein weiteres Zelt mit zwei Stangen zum aufspannen für 40€. Außerdem Schaute ich nach einer möglichst kleinen und leichten Luftmatratze, dies war für 40€ in einem Sportshop schnell gefunden. Parallel schaute ich nach Campingplätzen auf meiner Route dabei schaute ich in mehreren Portalen. Im Endeffekt war ich von der App Campercontact begeistert. Entsprechend der in der Nähe meiner Route befindlichen Cpingplätze passte ich die Route auf komoot an. Auf Grund des späten Flugs entschied ich mich  die Nacht vor der Ersten Etappe im Hotel zu verbringen. Nach dem der Plan für mich ca. Eine Woche vor dem gebuchten Flug perfekt schien fuhr ich noch ein Mountainbike Etappenrennen im Erzgebirge. Am Montag vor dem Trip ging es dann noch kurz nach Burscheid um bei Radsport Campana ein paar Ersatzteile und einen Radkarton zu besorgen.

    Zusammengefasst sah der Zeitplan wie folgt aus:
    Mi 28.07.
    🏡 Remscheid ✈️  🏨Mailand Malpense
    Do 29.07. 1. Etappe
    🏨 Mailand Malpense 🚲 🏕Cuneo
    Fr 30.07. 2. Etappe
    🏕 Cuneo 🚲 🏕 Barcelonette
    Sa 31.07. 3. Etappe
    🏕 Barcelonette 🚲 🏠 La Motte

    Flug von Düsseldorf nach Mailand Malpensa
    Nach der Arbeit ging es am Mittwoch Nachmittag mit Bike im Gepäck zum Flughafen Düsseldorf von dort startete das Flugzeug um 18:25 Uhr in Richtung Italien. Auf Grund der aktuellen Pandemie Lage galt es mehr zu beachten als sonst. Um 19:55 Uhr landete die Maschine am Flughafen Mailand Malpense. Dort stellte sich dann heraus, dass die Gedanken zur Entsorgung des Bikekartons umsonst waren. Direkt neben dem Gepäckband an dem auch das Spergepeck ausgegeben wird standen bereits zwei Kartons, neben denen meiner sicherlich nicht auffallen würde. So packte ich noch am Gepäckband den Karton aus, baute das Rad zusammen, befestigte das Gepäck und verlass den Flughafen. Von dort ging es zum 2,6 km entfernten Hotel. Nach dem checkin ging es noch kurz zum Italiener eine Pizza essen und dann ins Bett.

    1. Etappe Mailand Malpense - Cuneo
    Am Morgen klingelte um 07:00 Uhr der Wecker. Nach dem Aufstehen ging es zum Frühstücksbüffet, nach dem ich mich richtig satt gegessen und das Buffet für unterwegs noch ein bisschen geplündert habe ging es los. Um kurz nach 08:00 Uhr war ich startklar für die 1. Etappe mit 223,xx km und 850 hm. Ein Zwischenziel mit länger Pause setzte ich mir an diesem Tag in Turin. Gleich zu Beginn bemerkte ich Probleme beim schalten am Schaltwerk. Nach ca. 10 km störten mich die Probleme so sehr, dass ich stoppen musste um die Schaltung einzustellen. Die Route führte immer wieder über nur wenig befahrene Straßen und Feldwege. Ein weiterer Zwischenstopp an einem Supermarkt um die Trinkflaschen aufzufüllen ließ sich aufgrund der heißen Temperaturen nicht verhindern. Nach 110 km erreicht ich mein Zwischenziel, in Turin suchte ich mir dann eine Möglichkeit, um kurz Pause zu machen und noch eine Kleinigkeit neben den Brötchen vom Buffet zu essen. Bei 35 Grad und knallender Sonne ging es weiter in Richtung Cannue. Auch auf dem zweiten Teil waren die Flaschen plötzlich wieder leer und ich musste erneut einen Supermarkt anfahren. Die letzten Kilometer zum Campingplatz ging es dann bereits in den ersten Anstieg ca. 500 hm hoch, in dem ich dann erstmals zu spüren bekommen habe wie viel Gepäck ich dabei habe und was es mich an Kraft kostet es den Berg hoch zu befördern. Die ersten Gedanken an den folgenden Tag in den Alpen siebten mir durch den Kopf. Am Abend erreichte ich wie geplant den Campingplatz und konnte nach einem warmen Abendessen mein Zelt aufschlagen.

    2.Etappe Cuneo - Barcelonette
    Nach meiner ersten Nacht im Zelt wurde ich wieder um 07:00 Uhr von meinem Wecker geweckt. Diesmal wurde nach dem Aufstehen alles gepackt und gleich gestartet. Während der Fahrt gab es Brot das ich am Vortag eingekauft hatte zum Frühstück. Gleich am Anfang fuhr ich den Berg, in den ich bereits am Vortag gestartet bin weiter rauf. Auf halber Höhe in Richtung Gipfel auf 2800 m ü.M.S. fing es dann an zu Regnen, der Regen entwickelte sich schnell in einen Starken Schauer, so das ich binnen Sekunden klatschnass war. Kurze Zeit später ergab sich die Möglichkeit in einer Kirche unterzustellen. Wie der Regen nachließ ging es weiter, in Richtung Gipfel. Ich war begeistert nach jeder Kurve ergab sich eine neue Aussicht und alles war im Einklang. Das Zwischenziel auf dieser Etappe war eine Almhütte nach xx km vor der ersten Abfahrt. ….
    In der ersten Abfahrt hat es dann mit dem Gravel Bike so richtig gescheppert, nichts desto trotz hatte ich richtig Spaß und hab es genossen den halben Berg wieder runter zu fahren. Nach nur ein paar Metern durch ein Dorf ging es dann auch schon gleich wieder rein in den nächsten Berg. Der Untergrund wurde immer natürlicher und ausgesetzt, bis ich irgendwann vor einem Abschnitt stand, den man maximal hätte runter fahren können, damit nicht genug musste ich kurze Zeit erneut vom Rad runter und es ca. 5km den Berg rauf schieben und tragen. Erstmals war ich extrem unzufrieden mit der Routenführung, die mir auf Grund eines User Beitrags mit Bild in Komoot vorgeschlagen wurde. Der Weg erinnerte ehr an einen kletter Steig aber nicht an einen für Fahrräder jeglicher Art geeigneten Weg. Dennoch gab es auf dem zweiten Berg wunderschöne Aussichten. Die Abgahrt war hingegen größtenteils ohne Probleme fahrbar. Die letzten Meter zum Campingplatz machte ich dann wieder auf der Straße, auf der ich kurz vor Ziel noch von einer riesigen Schafherde aufgehalten wurde. Am Campingplatz erhielt ich dann leider die traurige Nachricht, dass sie komplett ausgebucht sind und mich nicht unterbringen können. Auf die schnelle schaute ich online nach einem weiteren Campingplatz in der Nähe, leider ohne Erfolg. Notgedrungen fuhr ich ein Hotel in der Nähe an, an der Rezeption machte der Hoteljeh mir dann schnell klar, dass ich für diese Nacht in diesem Ort keinen Schlafplatz mehr finden werde. Freundlicherweise rief er für mich einen Bekannten Hotelje an und konnte mir ein Zimmer im Nachbarort organisieren. Als wäre dass nicht genug, Bestand er darauf mich eben mit seinem Auto dort hin zu bringen. Da es mittlerweile schon spät war und ich nicht wollte dass irgendwas schiefgeht, nahm ich das Angebot dankend an. Ich schloss mein Rad an und wurde in den Nachbarort gefahren.

    3.Barcelonette - La Motte
    Ungewohnt wurde ich an diesem Morgen nicht von meinem Wecker geweckt, sondern von einer Schafherde, die über die Straße getrieben wurde. Nach einem Ausgiebigen Frühstück ging es dann schon auf die letzte Etappe Richtung La Motte. Zu Beginn stoppte ich kurz bei einem Supermarkt und füllte meine Vorräte für den Tag auf. Dann ging es nochmal 1200hm bergauf zum … . Von der Spitze führte eine Serpentinenstraße an Skihängen runter in ein Dorf, von dort an ging es dann von Ort zu Ort runter ins Tal. Auf dem Weg folgte ich einem Fluss La Verdon, der aus dem Berg entspringt, bis zu einem Stausee. Der Stausee hatte durch den Kalkanteil das blaueste Wasser was ich je gesehen habe. Später ging es dann noch über die große Staumauer die dieses zurückhält. Nach einer kurzen Mittagspause bei einer Pizza und schöner Aussieht. Ging es dann tatsächlich in den letzten Anstieg, der sich nochmal hoch schlängelte. Ab dort veränderte sich auch sehr die Natur, die Umgebung wurde sehr typisch für den Süden. Steine und Erde wurden röter und die Pflanzen Trockener. Somit erreichte ich an diesem Tag unser Ferienhaus und konnte die Etappe früher beenden wie als die Tage zuvor.

    Rückblickend waren es ein paar sehr schöne Tage und ich kann jedem empfehlen sowas zu machen.

    <a href="https://www.w3schools.com/">Visit W3Schools.com!</a>
</p>